package com.safekey.authenticator.autofill

/**
 * Heuristic engine that finds one-time-code fields inside an autofill
 * AssistStructure. Pure Kotlin on purpose — no android.* imports — so the
 * whole decision layer is exercised by JVM unit tests (OtpFieldDetectorTest).
 *
 * Evidence tiers, strongest first:
 *  1. HINT_2FA_APP — the field carries the official "2faAppOTPCode" hint
 *     (androidx.autofill.HintConstants.AUTOFILL_HINT_2FA_APP_OTP), which apps
 *     use to mark "fill me with a code generated by a 2FA app".
 *  2. HINT_SMS — the official "smsOTPCode" hint, including the per-digit
 *     "smsOTPCode{1..8}" variants produced by
 *     HintConstants.generateSmsOtpHintForCharacterPosition(). Widely used by
 *     apps and by Chrome (which maps autocomplete="one-time-code" to it).
 *  3. CONTEXT — the field id / hint text names an OTP explicitly
 *     ("verification code", "动态码", ...) and the field takes digits.
 *  4. WEAK — a digit-friendly field whose id merely says "code"/"token".
 *
 * Fields that look like *other* "code" fields (zip codes, promo codes, CVVs,
 * captchas, …) are rejected outright: staying quiet beats filling the wrong
 * box.
 */
data class FieldInfo(
    val idEntry: String? = null,
    val hintText: String? = null,
    val autofillHints: List<String> = emptyList(),
    /** Raw android.text.InputType bits; null when unknown (some WebView fields). */
    val rawInputType: Int? = null,
    val isFocused: Boolean = false,
    val isVisible: Boolean = true,
    val autofillable: Boolean = true,
)

enum class DetectionLevel { HINT_2FA_APP, HINT_SMS, CONTEXT, WEAK }

/** The chosen target field: [index] into the field list handed to detect(). */
data class Detection(val index: Int, val level: DetectionLevel, val score: Int, val reason: String)

object OtpFieldDetector {

    // Official hint values — see androidx.autofill.HintConstants
    // (developer.android.com/reference/androidx/autofill/HintConstants).
    private const val HINT_2FA_APP_OTP = "2faappotpcode" // AUTOFILL_HINT_2FA_APP_OTP
    private const val HINT_SMS_OTP = "smsotpcode"        // AUTOFILL_HINT_SMS_OTP (+ per-digit suffix)

    // android.text.InputType constants (stable since API 1).
    private const val TYPE_MASK_CLASS = 0x0000000f
    private const val TYPE_CLASS_NUMBER = 0x00000002
    private const val TYPE_CLASS_PHONE = 0x00000003

    /** Official hints that positively identify *other* field kinds — never fill. */
    private val REJECT_HINTS = setOf(
        "notapplicable", "promocode", "postalcode", "extendedpostalcode",
        "flightconfirmationcode", "giftcardnumber", "giftcardpin",
        "creditcardnumber", "creditcardsecuritycode",
        "phonecountrycode", "phonenumber", "phonenational", "phonenumberdevice",
        "wifipassword", "password", "newpassword", "username", "newusername",
        "emailaddress", "personname",
    )

    /** Substrings marking some other "code" field — reject outright. */
    private val REJECT_WORDS = listOf(
        "zip", "postal", "country", "area", "cvv", "cvc", "captcha",
        "coupon", "promo", "invite", "referral", "voucher",
        "邮政编码", "邀请", "优惠",
    )

    /** Unambiguous OTP wording — accepted even in non-numeric fields
     *  (Steam-style alphanumeric codes live in text boxes). */
    private val STRONG_WORDS = listOf(
        "otp", "totp", "2fa", "two-factor", "two factor", "one-time", "one time",
        "onetime", "authenticator code", "动态码", "动态密码", "一次性密码",
        "验证码", "校验码", "口令",
    )

    /** OTP wording believable only when the field clearly takes digits. */
    private val CONTEXT_WORDS = listOf(
        "verification code", "verify code", "auth code", "authentication code",
        "security code", "sms code", "code sent", "verificationcode",
        "verifycode", "authcode", "短信验证", "安全码", "双重验证", "两步验证",
    )

    /** Weak wording accepted only for digit-friendly fields. */
    private val WEAK_WORDS = listOf("code", "token")

    /** Best candidate, or null when nothing looks like an OTP field. */
    fun detect(fields: List<FieldInfo>): Detection? = detectAll(fields).firstOrNull()

    /** All viable candidates, best first — used by the diagnostic log. */
    fun detectAll(fields: List<FieldInfo>): List<Detection> =
        fields.asSequence()
            .mapIndexedNotNull { index, field -> score(index, field) }
            .sortedWith(compareByDescending<Detection> { it.score }.thenBy { it.index })
            .toList()

    private fun score(index: Int, field: FieldInfo): Detection? {
        if (!field.isVisible || !field.autofillable) return null
        val hints = field.autofillHints.map { it.lowercase() }
        if (hints.any { it in REJECT_HINTS }) return null

        val text = listOfNotNull(field.idEntry, field.hintText)
            .joinToString(" ")
            .lowercase()
            // "verification_code" / "one-time" must match the same keywords
            // as their spaced forms.
            .replace('_', ' ')
            .replace('-', ' ')
        if (text.isNotBlank() && REJECT_WORDS.any { it in text }) return null

        val focusedBonus = if (field.isFocused) 10 else 0
        val numeric = isNumeric(field.rawInputType)

        // 1) Explicit 2FA-app hint.
        if (hints.any { it == HINT_2FA_APP_OTP }) {
            return Detection(index, DetectionLevel.HINT_2FA_APP, 1000 + focusedBonus, "hint $HINT_2FA_APP_OTP")
        }

        // 2) smsOTPCode, including per-digit "smsOTPCodeN" groups; when the
        //    code is split into boxes, prefer the first position.
        if (hints.any { it.startsWith(HINT_SMS_OTP) }) {
            val position = hints.firstNotNullOfOrNull { h ->
                h.removePrefix(HINT_SMS_OTP).toIntOrNull()
            } ?: 0
            return Detection(index, DetectionLevel.HINT_SMS, 900 - position + focusedBonus, "hint $HINT_SMS_OTP/$position")
        }

        val haystack = (text + " " + hints.joinToString(" ")).lowercase()

        // 3) Strong wording — no digit requirement (alphanumeric codes exist).
        STRONG_WORDS.firstOrNull { it in haystack }?.let { word ->
            return Detection(index, DetectionLevel.CONTEXT, 600 + focusedBonus, "strong '$word'")
        }

        // 4) Context wording — needs a digit-friendly field.
        if (numeric) {
            CONTEXT_WORDS.firstOrNull { it in haystack }?.let { word ->
                return Detection(index, DetectionLevel.CONTEXT, 500 + focusedBonus + 30, "context '$word'")
            }
            WEAK_WORDS.firstOrNull { it in haystack }?.let { word ->
                return Detection(index, DetectionLevel.WEAK, 300 + focusedBonus + 20, "weak '$word'")
            }
        }
        return null
    }

    private fun isNumeric(rawInputType: Int?): Boolean {
        if (rawInputType == null) return false
        val cls = rawInputType and TYPE_MASK_CLASS
        return cls == TYPE_CLASS_NUMBER || cls == TYPE_CLASS_PHONE
    }
}
